language: python

python:
  - "3.3"
#  - "3.4"

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq libzmq3-dev

install:
  - python setup.py install

script:
  - python runtests.py -v
  - pip install msgpack-python
  - python runtests.py -v

cache: apt
