language: python

python:
  - "3.3"
  - "3.4"

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq libzmq3-dev
  - sudo apt-get install python3
  - sudo apt-get install python3-dev
  - sudo apt-get install python3-setuptools
  - sudo apt-get install python3-pip
  - pip install --user msgpack-python

install:
  - python setup.py install

script:
  - python runtests.py

