sudo: false

language: python

python:
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"

addons:
  apt:
    packages:
    - libzmq3-dev

install:
  - pip install pip setuptools wheel
  - python setup.py install
  - test $USE_MSGPACK == 1 && pip install msgpack-python || true
  - pip install flake8
  - pip install docutils
  - pip install codecov

script:
  - python -c "import zmq; print('ZMQ version:', zmq.zmq_version())"
  - flake8 aiozmq examples tests benchmarks
  - python setup.py check -rm
  - if python -c "import sys; sys.exit(sys.version_info < (3,5))"; then
        python setup.py check -s;
    fi
  - python runtests.py --coverage -v

after_success:
  - codecov

env:
  matrix:
    - USE_MSGPACK=1 PYTHONASYNCIODEBUG=1
    - USE_MSGPACK=0 PYTHONASYNCIODEBUG=1
    - USE_MSGPACK=1 PYTHONASYNCIODEBUG=0
    - USE_MSGPACK=0 PYTHONASYNCIODEBUG=0

cache:
- apt
- pip


deploy:
  provider: pypi
  user: andrew.svetlov
  password:
    secure: Z2giKAktwJWUWcWqgTUYgwvc46UmvvbAPzhTu6gIODN35MPGGsk6lXZiAb3znWx3UBRmGATT70pk6VkywW72dvi0BBwFyacGUsZu0Rk/5MU5L/EkXwd+hSEzlBpijrxu4AJGnvyxCydau+tZFTrelfcedgZlY/XeBI9iLoW+LQk=
  distributions: "sdist bdist_wheel"
  on:
    tags: true
    all_branches: true
    python: 3.5
