language: python

python:
  - "3.3"
  # - "3.4"

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq libzmq3-dev
  - sudo apt-get install -qq python3-flake8
  # - sudo apt-get install python3.4

install:
  - python setup.py install
  - test $USE_MSGPACK == 1 && pip install msgpack-python || true

script:
  - make pep
  - make flake
  - python runtests.py -v

env:
  global:
    - PYTHON=python
  matrix:
    - USE_MSGPACK=1
    - USE_MSGPACK=0

cache: apt
