language: python

python:
  - "3.3"
#  - "3.4"

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq libzmq3-dev

install:
  - python setup.py install
  - pip install msgpack-python

script:
  - python runtests.py

