language: python
sudo: false

python:
  - "3.3"
  - "3.4"

before_install:
  - apt-get install -qq libzmq3-dev

install:
  - python setup.py install
  - test $USE_MSGPACK == 1 && pip install msgpack-python || true
  - pip install pyflakes
  - pip install pep8
  - pip install docutils
  - pip install coveralls

script:
  - python -c "import zmq; print('ZMQ version:', zmq.zmq_version())"
  - pep8 aiozmq examples tests benchmarks
  - pyflakes .
  - python setup.py check -rms
  - python runtests.py --coverage -v

after_success:
  - coveralls

env:
  matrix:
    - USE_MSGPACK=1 PYTHONASYNCIODEBUG=1
    - USE_MSGPACK=0 PYTHONASYNCIODEBUG=1
    - USE_MSGPACK=1 PYTHONASYNCIODEBUG=0
    - USE_MSGPACK=0 PYTHONASYNCIODEBUG=0

cache: apt
