language: python

python:
  - "3.3"
  - "3.4"

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq libzmq3-dev

install:
  - python setup.py install
  - test $USE_MSGPACK == 1 && pip install msgpack-python || true
  - pip install pyflakes
  - pip install pep8
  - pip install docutils
  #- pip install coveralls

script:
  - python -c "import zmq; print('ZMQ version:', zmq.zmq_version())"
  - pep8 aiozmq examples tests benchmarks
  - pyflakes .
  - python runtests.py -v
  - python setup.py check -rms

env:
  matrix:
    - USE_MSGPACK=1
    - USE_MSGPACK=0

cache: apt
